<html>
<head>
	<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="<?php echo $this->baseUrl()?>/CSS/bootstrap.min.css">
 
	
</head>
<body>
 <a  class="btn" href="<?php echo $this->baseUrl().'/Zend/ZendSFS/public/index.php/users/list/'?>">Home</a>
      <a class="btn"  href="<?php echo $this->baseUrl().'/Zend/ZendSFS/public/index.php/users/add/'?>">Add User</a>
      
      <a  class="btn" href="<?php echo $this->baseUrl().'/Zend/ZendSFS/public/index.php/users/listadmin'?>">List Admins </a>
       <a  class="btn" href="<?php echo $this->baseUrl().'/Zend/ZendSFS/public/index.php/users/listbausers'?>">Ban Users </a>
        <a  class="btn" href="<?php echo $this->baseUrl().'/Zend/ZendSFS/public/index.php/users/system'?>">System Status </a>

<div class="row">
	<div class="col-sm-2"></div>
	<div class="col-sm-8">
		<br>
		<br>
		<br>
<table  class="table table-condensed" >
	<th>Username</th>
	<th>Email</th>
	<th>Gender</th>
	<th>Edit</th>
	<th>Delete</th>
	<th>Ban</th>
	<th>Make Admin</th>
<?php if($this->Users) { 

	for($i=0; $i<count($this->Users); $i++){
	if($this->Users[$i]['admin']==0 && $this->Users[$i]['ban']==0){
		echo "<tr>";
		echo '<td>'.$this->Users[$i]['username'].'</td>';
		echo '<td> '.$this->Users[$i]['useremail'].'</td>';
		echo '<td> '.$this->Users[$i]['gender'].'</td>';
		echo '<td><a class="btn btn-primary" href="'.$this->baseUrl().'/Zend/ZendSFS/public/index.php/Users/edit/user_id/'.$this->Users[$i]['user_id'].'"> Edit</a></td>';
		echo '<td><a  class="btn btn-danger" href="'.$this->baseUrl().'/Zend/ZendSFS/public/index.php/Users/delete/user_id/'.$this->Users[$i]['user_id'].'" >Delete</a></td>';
		echo '<td><a  class="btn btn-warning" href="'.$this->baseUrl().'/Zend/ZendSFS/public/index.php/Users/ban/user_id/'.$this->Users[$i]['user_id'].'" >Ban</a></td>';
		echo '<td><a  class="btn btn-info" href="'.$this->baseUrl().'/Zend/ZendSFS/public/index.php/Users/admin/user_id/'.$this->Users[$i]['user_id'].'" >Admin</a></td>';
		echo "</tr>";
}
	}
}

?>
</table>
</div>
</div>

</body>
</html>